# Generated by Django 5.2.7 on 2025-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
